In [2]:
import seaborn as sns 
#수업 시간 전 설정 
import matplotlib.pyplot as plt
%matplotlib inline
%config InlineBackend.figure_format='retina'

#한글 설정
plt.rc('font',family='Malgun Gothic')
plt.rc("axes",unicode_minus =False) # y축 

#경고 메세지 안 보이게
import warnings
warnings.filterwarnings(action='ignore')
#warnings.filterwarnings(action='default')

# 1. 지역

In [4]:
import pandas as pd 
region = pd.read_csv('data/(21)여성가족부_아동청소년보호기관정보_20200421.csv', encoding='cp949')
pd.options.display.max_columns=60
region.head(1)

,우편고지발송기관고유번호,아동청소년보호기관명,시도,주소지시군구,읍면동정보,행정동명,우편번호,기관주소,상세건물명1,상세건물명2,기관대표자,기관구분값,주소지지도X좌표,주소지지도Y좌표,완료여부,기관코드,EDU일련번호,EDU시도,EDU시군구,EDU읍면동,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23
0,461017,다솔 방과후교실,서울특별시,종로구,송월동,교남동,3180.0,서울특별시 종로구 통일로8길 16 (송월동),NaN,NaN,NaN,1.0,492340.0,1130522.0,Y,11110000069,32.0,서울특별시,종로구,교남동,NaN,NaN,NaN,NaN

## 정제된 데이터 (데이터 셋의 결측치 확인 및 시각화)

In [5]:
region.shape

(144229, 24)

In [3]:
region.dtypes

우편고지발송기관고유번호      int64
아동청소년보호기관명       object
시도               object
주소지시군구           object
읍면동정보            object
행정동명             object
우편번호            float64
기관주소             object
상세건물명1          float64
상세건물명2          float64
기관대표자           float64
기관구분값           float64
주소지지도X좌표        float64
주소지지도Y좌표        float64
완료여부             object
기관코드             object
EDU일련번호         float64
EDU시도            object
EDU시군구           object
EDU읍면동           object
Unnamed: 20     float64
Unnamed: 21     float64
Unnamed: 22     float64
Unnamed: 23      object
dtype: object

### 결측치 확인 및 시각화

In [4]:
region.drop([ "상세건물명1","상세건물명2","기관대표자","Unnamed: 20", "Unnamed: 21", "Unnamed: 22", "Unnamed: 23"],axis=1, inplace=True)

In [5]:
region.drop(["우편번호","EDU일련번호","EDU시도","EDU시군구","EDU읍면동","기관코드"],axis=1, inplace=True)

In [6]:
region.head(3)

,우편고지발송기관고유번호,아동청소년보호기관명,시도,주소지시군구,읍면동정보,행정동명,기관주소,기관구분값,주소지지도X좌표,주소지지도Y좌표,완료여부
0,461017,다솔 방과후교실,서울특별시,종로구,송월동,교남동,서울특별시 종로구 통일로8길 16 (송월동),1.0,492340.0,1130522.0,Y
1,461018,가회어린이집,서울특별시,종로구,가회동,가회동,서울특별시 종로구 북촌로12길 12-2 가회어린이집 (가회동),1.0,496876.0,1133972.0,Y
2,461019,노틀담방과후교실어린이집,서울특별시,종로구,가회동,가회동,서울특별시 종로구 북촌로 54 가회동,1.0,496816.0,1133916.0,Y

In [7]:
region.isnull().sum()

우편고지발송기관고유번호       0
아동청소년보호기관명         2
시도                 0
주소지시군구          1240
읍면동정보              0
행정동명              54
기관주소               3
기관구분값             14
주소지지도X좌표          69
주소지지도Y좌표          15
완료여부              14
dtype: int64

- "기관구분값"으로 정렬

In [16]:
region.sort_values(by="기관구분값" ,axis=0, inplace=True)

In [17]:
region.head()

,우편고지발송기관고유번호,아동청소년보호기관명,시도,주소지시군구,읍면동정보,행정동명,기관주소,기관구분값,주소지지도X좌표,주소지지도Y좌표,완료여부
0,461017,다솔 방과후교실,서울특별시,종로구,송월동,교남동,서울특별시 종로구 통일로8길 16 (송월동),1.0,492340.0,1130522.0,Y
30653,483267,미키24시어린이집,경기도,용인시 기흥구,상갈동,상갈동,"경기도 용인시 기흥구 금화로58번길 10 407동 105호(상갈동, 금화마을주공그린...",1.0,524331.0,1045428.0,Y
30654,483268,꿈동이어린이집,경기도,용인시 기흥구,상갈동,상갈동,"경기도 용인시 기흥구 금화로58번길 10 401동 105호(상갈동, 금화마을주공그린...",1.0,524258.0,1045290.0,Y
30655,483269,사랑어린이집,경기도,용인시 기흥구,상갈동,상갈동,"경기도 용인시 기흥구 금화로58번길 10 406동 101호(상갈동, 금화마을주공그린...",1.0,524431.0,1045540.0,Y
30656,483270,또래어린이집,경기도,용인시 기흥구,상갈동,상갈동,"경기도 용인시 기흥구 금화로58번길 10 408동 101호(상갈동, 금화마을주공그린...",1.0,524253.0,1045540.0,Y

In [18]:
middle_school=region.loc[region["기관구분값"]==4.0]

In [19]:
middle_school.head()

,우편고지발송기관고유번호,아동청소년보호기관명,시도,주소지시군구,읍면동정보,행정동명,기관주소,기관구분값,주소지지도X좌표,주소지지도Y좌표,완료여부
62479,515093,금마중학교,충청남도,홍성군,금마면,금마면,충청남도 홍성군 금마면 철마산길 182 (금마면),4.0,438195.0,867390.0,Y
62480,515094,서해삼육중학교,충청남도,홍성군,광천읍,광천읍,충청남도 홍성군 광천읍 홍남로705번길 23 . 서해삼육중고등학교 (광천읍),4.0,416584.0,835987.0,Y
62481,515095,홍동중학교,충청남도,홍성군,홍동면,홍동면,충청남도 홍성군 홍동면 광금남로 735 (홍동면),4.0,431206.0,851484.0,Y
62482,515096,홍성서부중학교,충청남도,홍성군,서부면,서부면,충청남도 홍성군 서부면 서부로 411,4.0,390155.0,853815.0,Y
62483,515097,홍성여자중학교,충청남도,홍성군,홍성읍,홍성읍,충청남도 홍성군 홍성읍 도청대로 29-21 (홍성읍),4.0,424125.0,864027.0,Y

In [21]:
middle_school.tail()

,우편고지발송기관고유번호,아동청소년보호기관명,시도,주소지시군구,읍면동정보,행정동명,기관주소,기관구분값,주소지지도X좌표,주소지지도Y좌표,완료여부
61413,514027,권선중학교,경기도,수원시 권선구,세류동,세류2동,경기도 수원시 권선구 경수대로 239 (세류동.권선중학교),4.0,503829.0,1041629.0,Y
61403,514017,소담중학교,세종특별자치시,NaN,소담동,소담동,세종특별자치시 남세종로 340 (소담동),4.0,567677.0,829003.0,Y
60665,513279,휘문중학교,서울특별시,강남구,대치동,대치2동,서울특별시 강남구 역삼로 541 (대치동),4.0,513812.0,1112546.0,Y
62820,515434,진상중학교,전라남도,광양시,진상면,진상면,전라남도 광양시 진상면 신시길 177 (진상면),4.0,663533.0,422983.0,Y
143982,596598,금오중학교,경상남도,양산시,동면,동면,경상남도 양산시 동면 금오16길 97,4.0,960704.0,511633.0,Y

### 아동청소년 보호기관중 청소년 보호기관은 제거  (기관구분값 4:중학교  5: 고등학교  제거)

In [24]:
middle_school

,우편고지발송기관고유번호,아동청소년보호기관명,시도,주소지시군구,읍면동정보,행정동명,기관주소,기관구분값,주소지지도X좌표,주소지지도Y좌표,완료여부
62479,515093,금마중학교,충청남도,홍성군,금마면,금마면,충청남도 홍성군 금마면 철마산길 182 (금마면),4.0,438195.0,867390.0,Y
62480,515094,서해삼육중학교,충청남도,홍성군,광천읍,광천읍,충청남도 홍성군 광천읍 홍남로705번길 23 . 서해삼육중고등학교 (광천읍),4.0,416584.0,835987.0,Y
62481,515095,홍동중학교,충청남도,홍성군,홍동면,홍동면,충청남도 홍성군 홍동면 광금남로 735 (홍동면),4.0,431206.0,851484.0,Y
62482,515096,홍성서부중학교,충청남도,홍성군,서부면,서부면,충청남도 홍성군 서부면 서부로 411,4.0,390155.0,853815.0,Y
62483,515097,홍성여자중학교,충청남도,홍성군,홍성읍,홍성읍,충청남도 홍성군 홍성읍 도청대로 29-21 (홍성읍),4.0,424125.0,864027.0,Y
...,...,...,...,...,...,...,...,...,...,...,...
61413,514027,권선중학교,경기도,수원시 권선구,세류동,세류2동,경기도 수원시 권선구 경수대로 239 (세류동.권선중학교),4.0,503829.0,1041629.0,Y
61403,514017,소담중학교,세종특별자치시,NaN,소담동,소담동,세종특별자치시 남세종로 340 (소담동),4.0,567677.0,829003.0,Y
60665,513279,휘문중학교,서울특별시,강남구,대치동,대치2동,서울특별시 강남구 역삼로 541 (대치동),4.0,513812.0,1112546.0,Y
62820,515434,진상중학교,전라남도,광양시,진상면,진상면,전라남도 광양시 진상면 신시길 177 (진상면),4.0,663533.0,422983.0,Y
143982,596598,금오중학교,경상남도,양산시,동면,동면,경상남도 양산시 동면 금오16길 97,4.0,960704.0,511633.0,Y

In [8]:
middle_school=region.loc[region["기관구분값"]==4.0]
high_school=region.loc[region["기관구분값"]==5.0]
#index명 부여 해서 삭제  https://blog.naver.com/PostView.nhn?blogId=rising_n_falling&logNo=221629326893

In [23]:
middle_school.notnull().sum()

우편고지발송기관고유번호    3237
아동청소년보호기관명      3237
시도              3237
주소지시군구          3213
읍면동정보           3237
행정동명            3237
기관주소            3237
기관구분값           3237
주소지지도X좌표        3237
주소지지도Y좌표        3237
완료여부            3237
dtype: int64

In [12]:
middle_school.head()

,우편고지발송기관고유번호,아동청소년보호기관명,시도,주소지시군구,읍면동정보,행정동명,기관주소,기관구분값,주소지지도X좌표,주소지지도Y좌표,완료여부
60328,512942,서울대학교사범대학부설여자중학교,서울특별시,종로구,이화동,이화동,서울특별시 종로구 대학로 64 . 서울대학교사범대학부설여자중학교 (이화동),4.0,500885.0,1132886.0,Y
60329,512943,경신중학교,서울특별시,종로구,혜화동,혜화동,서울특별시 종로구 혜화로 74 (혜화동.경신중고등학교),4.0,500053.0,1136843.0,Y
60330,512944,대신중학교,서울특별시,종로구,행촌동,교남동,서울특별시 종로구 사직로 9 (행촌동),4.0,491619.0,1131654.0,Y
60331,512945,덕성여자중학교,서울특별시,종로구,송현동,삼청동,서울특별시 종로구 율곡로3길 49 (송현동),4.0,495968.0,1132974.0,Y
60332,512946,동성중학교,서울특별시,종로구,혜화동,혜화동,서울특별시 종로구 대학로 156 동성중학교 (혜화동 90-7),4.0,500422.0,1134767.0,Y

### ② reguib변수의 결측치를 제외한 데이터 개수 및 dtype들을 출력하고 + 변수가 사용되는 메모리 사용량 확인한다. (info)

In [ ]:
region.notnull().sum()

In [ ]:
region.info()

### ③ 결측치를 확인하고 컬측치가 없는 컬럼을 포함하여 시각화(정렬전 bar plot, barh plot, 정렬 후 bar plot, barh plot)

## region 데이터 셋의 값을 가져온다(loc함수, iloc함수등을 사용하기도 하고 사용하지 않기도 하며 서브셋을 가져온다)

① 기관구분값 필드만 가져온다

② 기관구분값 종류별 데이터수를 가져온다(df.상호명.value_counts()이용)

③ “아동청소년보호기관명”과 "기관주소” 컬럼 가져오기

In [ ]:
# 1:어린이집  2: 유치원   3: 초등학교  4:중학교  5: 고등학교  7: 사무소, 센터   8:학원, 독서실  9: 아동센터 
# 해당 데이터에서 청소년 기관은 제거. 아동 보호기관만 남게  ********************************

In [29]:
region_ins_code = region.groupby(region["기관구분값"]).count()
region_ins_code

,우편고지발송기관고유번호,아동청소년보호기관명,시도,주소지시군구,읍면동정보,행정동명,기관주소,주소지지도X좌표,주소지지도Y좌표,완료여부
기관구분값,,,,,,,,,,
1.0,37369,37369,37369,37010,37369,37369,37369,37369,37369,37369
2.0,8312,8311,8312,8252,8312,8260,8312,8259,8312,8312
3.0,6281,6281,6281,6232,6281,6281,6281,6281,6280,6281
4.0,3237,3237,3237,3213,3237,3237,3237,3237,3237,3237
5.0,2358,2358,2358,2340,2358,2358,2358,2358,2358,2358
6.0,178,178,178,177,178,178,178,178,178,178
7.0,3578,3578,3578,3559,3578,3578,3578,3578,3578,3578
8.0,77866,77865,77866,77172,77866,77864,77866,77864,77866,77866
9.0,4234,4234,4234,4221,4234,4234,4234,4234,4234,4234
10.0,802,802,802,799,802,802,802,802,802,802

# 강원도

In [33]:
kwangwon= region.loc[region["시도"]=="강원도"]

In [54]:
# 강원 & 1: 어린이집
kwangwon["기관구분값"].value_counts()

# 강원 &  2: 유치원
# 강원 &  3: 초등학교
# 강원 &  7: 사무소, 센터
# 강원 &  8:학원, 독서실
# 강원 &  9: 아동센터

8.0     2182
1.0     1036
3.0      378
2.0      374
7.0      193
9.0      174
4.0      162
5.0      115
10.0      80
6.0        7
Name: 기관구분값, dtype: int64

# 경기도

In [36]:
Gyeonggi= region.loc[region["시도"]=="경기도"]

In [55]:
Gyeonggi["기관구분값"].value_counts()

# 서울 & 1: 어린이집
# 서울 & 2: 유치원
# 서울 & 3: 초등학교
# 서울 & 7: 사무소, 센터
# 서울 & 8:학원, 독서실
# 서울 & 9: 아동센터

8.0     21369
1.0     11305
2.0      2251
3.0      1308
9.0       789
4.0       635
7.0       575
5.0       475
10.0      153
6.0        36
Name: 기관구분값, dtype: int64

# 경상남도

In [37]:
Gyeongsangnam= region.loc[region["시도"]=="경상남도"]

In [56]:
Gyeongsangnam["기관구분값"].value_counts()
# 서울 & 1: 어린이집
# 서울 & 2: 유치원
# 서울 & 3: 초등학교
# 서울 & 7: 사무소, 센터
# 서울 & 8:학원, 독서실
# 서울 & 9: 아동센터

8.0     5842
1.0     2777
2.0      684
3.0      521
7.0      312
9.0      270
4.0      267
5.0      190
10.0      76
6.0       10
Name: 기관구분값, dtype: int64

# 경상북도

In [38]:
Gyeongsangbuk= region.loc[region["시도"]=="경상북도"]

In [57]:
Gyeongsangbuk["기관구분값"].value_counts()
# 서울 & 1: 어린이집
# 서울 & 2: 유치원
# 서울 & 3: 초등학교
# 서울 & 7: 사무소, 센터
# 서울 & 8:학원, 독서실
# 서울 & 9: 아동센터

8.0     3443
1.0     1844
2.0      673
3.0      507
7.0      345
9.0      275
4.0      269
5.0      184
10.0      66
6.0        8
Name: 기관구분값, dtype: int64

# 광주광역시

In [39]:
Gwangju= region.loc[region["시도"]=="광주광역시"]

In [58]:
Gwangju["기관구분값"].value_counts()
# 서울 & 1: 어린이집
# 서울 & 2: 유치원
# 서울 & 3: 초등학교
# 서울 & 7: 사무소, 센터
# 서울 & 8:학원, 독서실
# 서울 & 9: 아동센터

8.0     3132
1.0     1122
9.0      315
2.0      290
3.0      156
7.0       95
4.0       90
5.0       67
10.0      13
6.0        5
Name: 기관구분값, dtype: int64

# 대구광역시

In [40]:
Daegu=region.loc[region["시도"]=="대구광역시"]

In [59]:
Daegu["기관구분값"].value_counts()
# 서울 & 1: 어린이집
# 서울 & 2: 유치원
# 서울 & 3: 초등학교
# 서울 & 7: 사무소, 센터
# 서울 & 8:학원, 독서실
# 서울 & 9: 아동센터

8.0     3803
1.0     1322
2.0      346
3.0      228
9.0      199
7.0      143
4.0      125
5.0       93
10.0      14
6.0        9
Name: 기관구분값, dtype: int64

# 대전광역시

In [41]:
Daejeon=region.loc[region["시도"]=="대전광역시"]

In [60]:
Daejeon["기관구분값"].value_counts()
# 서울 & 1: 어린이집
# 서울 & 2: 유치원
# 서울 & 3: 초등학교
# 서울 & 7: 사무소, 센터
# 서울 & 8:학원, 독서실
# 서울 & 9: 아동센터

8.0     1980
1.0     1288
2.0      261
3.0      150
9.0      142
4.0       88
7.0       79
5.0       62
10.0      16
6.0        5
Name: 기관구분값, dtype: int64

# 부산광역시

In [42]:
Busan = region.loc[region["시도"]=="부산광역시"]

In [61]:
Busan["기관구분값"].value_counts()
# 서울 & 1: 어린이집
# 서울 & 2: 유치원
# 서울 & 3: 초등학교
# 서울 & 7: 사무소, 센터
# 서울 & 8:학원, 독서실
# 서울 & 9: 아동센터

8.0     4537
1.0     1848
2.0      386
3.0      304
9.0      211
7.0      204
4.0      172
5.0      144
10.0      25
6.0       15
Name: 기관구분값, dtype: int64

# 서울특별시

In [43]:
Seoul=region.loc[region["시도"]=="서울특별시"]

In [62]:
Seoul["기관구분값"].value_counts()
# 서울 & 1: 어린이집
# 서울 & 2: 유치원
# 서울 & 3: 초등학교
# 서울 & 7: 사무소, 센터
# 서울 & 8:학원, 독서실
# 서울 & 9: 아동센터

8.0     12381
1.0      5696
3.0       603
9.0       456
2.0       446
7.0       425
4.0       385
5.0       321
10.0       63
6.0        31
Name: 기관구분값, dtype: int64

# 세종특별자치시

In [44]:
Sejong=region.loc[region["시도"]=="세종특별자치시"]

In [63]:
Sejong["기관구분값"].value_counts()
# 서울 & 1: 어린이집
# 서울 & 2: 유치원
# 서울 & 3: 초등학교
# 서울 & 7: 사무소, 센터
# 서울 & 8:학원, 독서실
# 서울 & 9: 아동센터

8.0     694
1.0     359
2.0      60
3.0      49
4.0      24
7.0      19
5.0      18
9.0      13
10.0      3
6.0       1
Name: 기관구분값, dtype: int64

# 울산광역시

In [45]:
Ulsan=region.loc[region["시도"]=="울산광역시"]

In [64]:
Ulsan["기관구분값"].value_counts()
# 서울 & 1: 어린이집
# 서울 & 2: 유치원
# 서울 & 3: 초등학교
# 서울 & 7: 사무소, 센터
# 서울 & 8:학원, 독서실
# 서울 & 9: 아동센터

8.0     2461
1.0      842
2.0      199
3.0      122
4.0       63
5.0       57
9.0       56
7.0       56
10.0      10
6.0        4
Name: 기관구분값, dtype: int64

# 인천광역시

In [46]:
Incheon=region.loc[region["시도"]=="인천광역시"]

In [65]:
Incheon["기관구분값"].value_counts()
# 서울 & 1: 어린이집
# 서울 & 2: 유치원
# 서울 & 3: 초등학교
# 서울 & 7: 사무소, 센터
# 서울 & 8:학원, 독서실
# 서울 & 9: 아동센터

8.0     3741
1.0     2049
2.0      404
3.0      261
9.0      179
7.0      158
4.0      135
5.0      125
10.0      28
6.0        9
Name: 기관구분값, dtype: int64

# 전라남도

In [47]:
Jeollanam=region.loc[region["시도"]=="전라남도"]

In [66]:
Jeollanam["기관구분값"].value_counts()
# 서울 & 1: 어린이집
# 서울 & 2: 유치원
# 서울 & 3: 초등학교
# 서울 & 7: 사무소, 센터
# 서울 & 8:학원, 독서실
# 서울 & 9: 아동센터

8.0     2697
1.0     1147
2.0      497
3.0      465
9.0      380
7.0      323
4.0      254
5.0      142
10.0      58
6.0        8
Name: 기관구분값, dtype: int64

# 전라북도

In [48]:
Jeollabuk=region.loc[region["시도"]=="전라북도"]

In [67]:
Jeollabuk["기관구분값"].value_counts()
# 서울 & 1: 어린이집
# 서울 & 2: 유치원
# 서울 & 3: 초등학교
# 서울 & 7: 사무소, 센터
# 서울 & 8:학원, 독서실
# 서울 & 9: 아동센터

8.0     3617
1.0     1288
2.0      503
3.0      423
9.0      285
7.0      244
4.0      209
5.0      134
10.0      54
6.0       10
Name: 기관구분값, dtype: int64

# 제주특별자치도

In [49]:
Jeju=region.loc[region["시도"]=="제주특별자치도"]

In [68]:
Jeju["기관구분값"].value_counts()
# 서울 & 1: 어린이집
# 서울 & 2: 유치원
# 서울 & 3: 초등학교
# 서울 & 7: 사무소, 센터
# 서울 & 8:학원, 독서실
# 서울 & 9: 아동센터

8.0     1047
1.0      504
2.0      122
3.0      118
9.0       67
10.0      51
4.0       45
7.0       43
5.0       30
6.0        3
Name: 기관구분값, dtype: int64

# 충청남도

In [50]:
Chungcheongnam=region.loc[region["시도"]=="제주특별자치도"]

In [69]:
Chungcheongnam["기관구분값"].value_counts()

# 서울 & 1: 어린이집
# 서울 & 2: 유치원
# 서울 & 3: 초등학교
# 서울 & 7: 사무소, 센터
# 서울 & 8:학원, 독서실
# 서울 & 9: 아동센터

8.0     1047
1.0      504
2.0      122
3.0      118
9.0       67
10.0      51
4.0       45
7.0       43
5.0       30
6.0        3
Name: 기관구분값, dtype: int64

# 충청북도

In [53]:
Chungcheongbuk=region.loc[region["시도"]=="충청북도"]

In [70]:
Chungcheongbuk["기관구분값"].value_counts()

# 서울 & 1: 어린이집
# 서울 & 2: 유치원
# 서울 & 3: 초등학교
# 서울 & 7: 사무소, 센터
# 서울 & 8:학원, 독서실
# 서울 & 9: 아동센터

8.0     2131
1.0     1130
2.0      318
3.0      268
9.0      185
7.0      154
4.0      126
5.0       84
10.0      44
6.0       10
Name: 기관구분값, dtype: int64

기관구분값이 6인 것 찾아

# 지역별  기관코드의 개수를 도출하고 시각화하기

In [ ]:
#보호기관갯수 (청소년 보호기관을 제거 해야 )*********************************************

In [30]:
region.groupby(region["시도"])["아동청소년보호기관명"].count()

시도
강원도         4703
경기도        38895
경상남도       10948
경상북도        7616
광주광역시       5285
대구광역시       6284
대전광역시       4071
부산광역시       7847
서울특별시      20810
세종특별자치시     1240
울산광역시       3870
인천광역시       7089
전라남도        5975
전라북도        6767
제주특별자치도     2030
충청남도        6347
충청북도        4450
Name: 아동청소년보호기관명, dtype: int64

In [ ]:
#region.sort_values(ascending=False).plot(kind="bar", rot=0, figsize=(10,3))

# 기관코트 서브셋을 이용한 분석

① “기관코트”가 ...인 서브셋을 변수 re_code에 할당하고 확인

In [ ]:
#서울이면서 기관1,  2, 3,7,8,9
# 강원도         4703
# 경기도        38895
# 경상남도       10948
# 경상북도        7616
# 광주광역시       5285
# 대구광역시       6284
# 대전광역시       4071
# 부산광역시       7847
# 서울특별시      20810
# 세종특별자치시     1240
# 울산광역시       3870
# 인천광역시       7089
# 전라남도        5975
# 전라북도        6767
# 제주특별자치도     2030
# 충청남도        6347
# 충청북도        4450


② “기관코트”가 ..이면서, "시도명”이 '서울'인 데이터만 가져와 “기관토드명”별로 빈도수를 구함(loc함수를 이용 vs loc함수 이용안함)

# 2. 신고자 유형 및 건수

In [72]:
report= pd.read_csv('data/보건복지부_아동학대 신고자 유형 및 신고접수 현황정보_20181231.csv', encoding='cp949')
report.head()

,기간,구분,아동학대의심사례 응급아동학대의심사례,아동학대의심사례,일반상담,동일신고,해외발생사례,교직원,의료인,아동복지시설종사자,장애인복지시설종사자,보육교직원,"유치원교직원,강사",학원강사,소방구급대원,성매매피해시설상담소종사자,한부모가족복지시설종사자,가족폭력상담소보호시설종사자,사회복지전담공무원,아이돌보미,취약계층아동통합서비스지원인력,아동보호전문기관상담원,가정위탁지원센터종사자,아동복지전담공무원,건강가정지원센터종사자,다문화가족지원센터종사자,사회복지시설종사자,성폭력피해자보호시설종사자,응급구조사,의료기사,"청소년시설,단체종사자","청소년보호센터,재활센터종사자",정신보건센터종사자,아동본인,부모,"형제,자매",친인척,"이웃,친구",경찰,종교인,사회복지관련종사자,낯선사람,익명,아동보호전문기관장과 종사자,의료사회복지사,법원
0,2013,중앙,1,0,2,2.0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0
1,2013,서울,186,1118,596,8.0,0,87,17,27,0,21,0,1,1,1,0,9,215,0,0,NaN,0,15,4,1,12,2,0,1,20,5,7,26,184,4,42,217,103,5,198,15,1,0,NaN,63
2,2013,부산,19,408,70,0.0,0,54,2,10,0,9,0,0,0,1,2,22,50,0,0,NaN,0,2,0,1,7,2,0,0,2,2,5,4,88,4,12,48,16,0,60,8,2,0,NaN,14
3,2013,대구,61,343,47,2.0,0,39,6,29,0,5,5,0,0,0,3,4,12,0,0,NaN,0,1,0,1,14,8,0,0,2,3,4,10,60,1,12,20,21,0,122,4,3,0,NaN,15
4,2013,인천,69,467,201,1.0,0,31,7,10,4,5,0,0,1,0,7,16,75,0,0,NaN,1,29,1,2,15,3,0,0,1,1,0,3,56,2,19,80,54,0,88,4,0,0,NaN,21

In [ ]:
# 연도별, 지역별. 유형별.  [신고자 수 많은 유형. 어느지역과. => 그 시설 더 많이 건설 혹은 더 많은 그런 사람들 아동인식 신고 교육.]

## 연도별

In [94]:
report.loc[report["구분"]=="서울"]

,기간,구분,아동학대의심사례 응급아동학대의심사례,아동학대의심사례,일반상담,동일신고,해외발생사례,교직원,의료인,아동복지시설종사자,장애인복지시설종사자,보육교직원,"유치원교직원,강사",학원강사,소방구급대원,성매매피해시설상담소종사자,한부모가족복지시설종사자,가족폭력상담소보호시설종사자,사회복지전담공무원,아이돌보미,취약계층아동통합서비스지원인력,아동보호전문기관상담원,가정위탁지원센터종사자,아동복지전담공무원,건강가정지원센터종사자,다문화가족지원센터종사자,사회복지시설종사자,성폭력피해자보호시설종사자,응급구조사,의료기사,"청소년시설,단체종사자","청소년보호센터,재활센터종사자",정신보건센터종사자,아동본인,부모,"형제,자매",친인척,"이웃,친구",경찰,종교인,사회복지관련종사자,낯선사람,익명,아동보호전문기관장과 종사자,의료사회복지사,법원
1,2013,서울,186,1118,596,8.0,0,87,17,27,0,21,0,1,1,1,0,9,215,0,0,NaN,0,15,4,1,12,2,0,1,20,5,7,26,184,4,42,217,103,5,198,15,1,0,NaN,63
18,2014,서울,304,1333,686,13.0,0,221,26,29,0,21,7,2,0,0,2,9,54,0,6,NaN,0,6,0,1,21,1,1,0,14,1,15,120,231,13,51,186,229,3,287,28,24,0,NaN,28
35,2015,서울,270,1683,361,8.0,3,248,23,25,6,43,7,0,0,0,2,14,49,0,24,NaN,0,1,0,4,30,4,0,0,13,3,8,198,398,20,40,136,59,4,450,28,20,0,NaN,96
52,2016,서울,454,2986,587,34.0,0,460,48,51,0,34,4,11,2,2,0,9,127,0,10,67.0,0,24,7,0,54,3,1,0,19,9,3,346,785,57,85,331,165,2,438,90,51,54,NaN,91
69,2017,서울,275,3121,412,37.0,0,579,54,39,3,62,5,1,2,1,1,11,112,19,0,3.0,2,3,8,1,30,8,0,19,14,0,0,454,735,26,67,235,67,1,30,81,27,586,10.0,100
86,2018,서울,98,3285,237,43.0,0,702,40,34,7,20,10,2,6,0,4,5,50,30,0,14.0,2,1,1,0,24,19,0,9,6,1,0,455,844,51,64,211,24,7,40,54,20,523,5.0,0

In [97]:
report.loc[report["구분"]=="서울"]["아동학대의심사례"].value_counts(ascending=True)

3285    1
3121    1
2986    1
1683    1
1333    1
1118    1
Name: 아동학대의심사례, dtype: int64

### 2018년도 신고유형 많은 순으로

In [104]:
#2018년도 
y2018=report.loc[report["기간"]==2018]
y2018

,기간,구분,아동학대의심사례 응급아동학대의심사례,아동학대의심사례,일반상담,동일신고,해외발생사례,교직원,의료인,아동복지시설종사자,장애인복지시설종사자,보육교직원,"유치원교직원,강사",학원강사,소방구급대원,성매매피해시설상담소종사자,한부모가족복지시설종사자,가족폭력상담소보호시설종사자,사회복지전담공무원,아이돌보미,취약계층아동통합서비스지원인력,아동보호전문기관상담원,가정위탁지원센터종사자,아동복지전담공무원,건강가정지원센터종사자,다문화가족지원센터종사자,사회복지시설종사자,성폭력피해자보호시설종사자,응급구조사,의료기사,"청소년시설,단체종사자","청소년보호센터,재활센터종사자",정신보건센터종사자,아동본인,부모,"형제,자매",친인척,"이웃,친구",경찰,종교인,사회복지관련종사자,낯선사람,익명,아동보호전문기관장과 종사자,의료사회복지사,법원
85,2018,중앙,0,0,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0
86,2018,서울,98,3285,237,43.0,0,702,40,34,7,20,10,2,6,0,4,5,50,30,0,14.0,2,1,1,0,24,19,0,9,6,1,0,455,844,51,64,211,24,7,40,54,20,523,5.0,0
87,2018,부산,33,2178,79,9.0,0,663,14,23,11,5,13,2,0,0,5,7,33,27,2,7.0,1,2,3,0,47,32,1,4,7,0,1,220,360,16,22,91,10,0,15,26,14,366,0.0,8
88,2018,대구,58,1507,146,45.0,0,222,14,38,2,5,1,3,6,1,0,11,28,6,5,1.0,5,3,1,0,23,10,0,6,8,0,1,235,316,23,22,73,8,2,11,27,3,402,0.0,2
89,2018,인천,24,2088,244,33.0,0,334,24,9,3,21,11,2,6,0,0,5,53,6,4,0.0,3,1,3,0,16,2,1,15,0,0,0,336,373,36,33,222,52,2,6,21,6,393,4.0,1
90,2018,광주,37,1088,21,11.0,0,148,10,26,2,0,1,0,0,1,1,4,25,3,3,11.0,3,2,0,0,3,1,1,2,11,0,0,145,179,8,33,58,6,0,9,19,7,368,5.0,1
91,2018,대전,39,1086,60,9.0,0,178,16,10,0,21,5,0,1,0,0,11,50,1,0,4.0,0,0,0,0,15,4,0,0,0,0,0,273,219,22,36,91,5,0,13,17,48,54,1.0,0
92,2018,울산,10,848,61,10.0,0,135,9,7,0,3,2,0,0,0,0,6,13,3,1,1.0,0,1,1,0,8,12,0,2,1,0,0,98,133,3,14,38,3,0,1,13,3,321,6.0,7
93,2018,경기,346,8041,694,100.0,1,1609,99,85,16,61,25,4,0,1,2,38,141,35,2,13.0,2,12,14,0,52,17,2,48,13,1,1,1218,1612,101,131,523,175,3,62,130,40,1817,24.0,7
94,2018,강원,59,1392,74,19.0,0,288,5,9,3,8,3,0,1,0,0,6,36,17,0,7.0,4,2,0,0,19,0,0,15,12,2,0,126,187,6,19,30,11,1,3,7,16,574,10.0,1
95,2018,충북,103,1006,113,29.0,0,165,7,11,1,4,7,3,1,0,0,11,34,12,0,0.0,0,3,13,0,2,0,0,21,6,0,0,130,147,12,23,56,9,1,4,4,5,369,3.0,4
96,2018,충남,65,1766,199,16.0,0,461,15,37,0,10,7,1,1,0,0,13,47,16,1,5.0,1,1,2,0,5,10,0,23,3,0,0,289,267,21,26,73,26,1,10,21,8,373,4.0,0
97,2018,전북,88,1850,145,13.0,0,367,12,30,4,14,11,1,0,1,0,58,40,22,5,0.0,2,0,4,0,22,5,5,53,13,0,0,151,260,29,52,104,17,1,44,15,12,544,0.0,2
98,2018,전남,58,2025,72,30.0,0,512,14,42,0,10,6,0,0,0,0,31,32,12,0,1.0,1,9,5,0,7,3,0,9,22,0,0,277,314,26,36,71,21,0,15,28,10,532,0.0,0
99,2018,경북,94,2263,240,43.0,0,304,24,21,1,19,8,0,2,0,2,45,45,9,0,6.0,5,9,0,0,11,6,0,32,63,0,0,255,469,18,48,97,26,0,36,25,20,695,2.0,0
100,2018,경남,59,1239,28,3.0,0,257,19,12,6,7,2,0,0,4,0,28,29,7,2,2.0,1,4,1,0,21,0,1,15,3,0,1,133,246,13,30,86,7,0,3,13,3,304,1.0,1
101,2018,제주,14,589,47,7.0,0,41,2,17,0,4,1,0,0,0,0,3,2,5,0,0.0,1,0,0,0,1,0,0,0,0,0,0,143,147,15,15,30,5,0,3,20,12,113,1.0,0
102,2018,세종,2,94,4,0.0,0,20,1,0,0,1,2,0,0,0,0,1,0,0,0,0.0,0,2,0,0,0,0,0,1,0,0,0,28,16,3,3,5,1,0,0,3,1,8,0.0,0

### 신고 유형 <br>
https://www.korea.kr/news/top50View.do?newsId=148863606&cateId=people_news

In [ ]:
# report_type이 신고유형을 담은 변수

In [ ]:
report.drop(["아동학대의심사례 응급아동학대의심사례","아동학대의심사례","일반상담","동일신고","해외발생사례"],axis=1)

In [157]:
report_type=report.drop(["동일신고","해외발생사례"],axis=1)
report_type

,기간,구분,교직원,의료인,아동복지시설종사자,장애인복지시설종사자,보육교직원,"유치원교직원,강사",학원강사,소방구급대원,성매매피해시설상담소종사자,한부모가족복지시설종사자,가족폭력상담소보호시설종사자,사회복지전담공무원,아이돌보미,취약계층아동통합서비스지원인력,아동보호전문기관상담원,가정위탁지원센터종사자,아동복지전담공무원,건강가정지원센터종사자,다문화가족지원센터종사자,사회복지시설종사자,성폭력피해자보호시설종사자,응급구조사,의료기사,"청소년시설,단체종사자","청소년보호센터,재활센터종사자",정신보건센터종사자,아동본인,부모,"형제,자매",친인척,"이웃,친구",경찰,종교인,사회복지관련종사자,낯선사람,익명,아동보호전문기관장과 종사자,의료사회복지사,법원
0,2013,중앙,0,0,0,0,0,0,0,0,0,0,0,1,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0
1,2013,서울,87,17,27,0,21,0,1,1,1,0,9,215,0,0,NaN,0,15,4,1,12,2,0,1,20,5,7,26,184,4,42,217,103,5,198,15,1,0,NaN,63
2,2013,부산,54,2,10,0,9,0,0,0,1,2,22,50,0,0,NaN,0,2,0,1,7,2,0,0,2,2,5,4,88,4,12,48,16,0,60,8,2,0,NaN,14
3,2013,대구,39,6,29,0,5,5,0,0,0,3,4,12,0,0,NaN,0,1,0,1,14,8,0,0,2,3,4,10,60,1,12,20,21,0,122,4,3,0,NaN,15
4,2013,인천,31,7,10,4,5,0,0,1,0,7,16,75,0,0,NaN,1,29,1,2,15,3,0,0,1,1,0,3,56,2,19,80,54,0,88,4,0,0,NaN,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,2018,전남,512,14,42,0,10,6,0,0,0,0,31,32,12,0,1.0,1,9,5,0,7,3,0,9,22,0,0,277,314,26,36,71,21,0,15,28,10,532,0.0,0
99,2018,경북,304,24,21,1,19,8,0,2,0,2,45,45,9,0,6.0,5,9,0,0,11,6,0,32,63,0,0,255,469,18,48,97,26,0,36,25,20,695,2.0,0
100,2018,경남,257,19,12,6,7,2,0,0,4,0,28,29,7,2,2.0,1,4,1,0,21,0,1,15,3,0,1,133,246,13,30,86,7,0,3,13,3,304,1.0,1
101,2018,제주,41,2,17,0,4,1,0,0,0,0,3,2,5,0,0.0,1,0,0,0,1,0,0,0,0,0,0,143,147,15,15,30,5,0,3,20,12,113,1.0,0
102,2018,세종,20,1,0,0,1,2,0,0,0,0,1,0,0,0,0.0,0,2,0,0,0,0,0,1,0,0,0,28,16,3,3,5,1,0,0,3,1,8,0.0,0

In [158]:
report_type.head()

,기간,구분,교직원,의료인,아동복지시설종사자,장애인복지시설종사자,보육교직원,"유치원교직원,강사",학원강사,소방구급대원,성매매피해시설상담소종사자,한부모가족복지시설종사자,가족폭력상담소보호시설종사자,사회복지전담공무원,아이돌보미,취약계층아동통합서비스지원인력,아동보호전문기관상담원,가정위탁지원센터종사자,아동복지전담공무원,건강가정지원센터종사자,다문화가족지원센터종사자,사회복지시설종사자,성폭력피해자보호시설종사자,응급구조사,의료기사,"청소년시설,단체종사자","청소년보호센터,재활센터종사자",정신보건센터종사자,아동본인,부모,"형제,자매",친인척,"이웃,친구",경찰,종교인,사회복지관련종사자,낯선사람,익명,아동보호전문기관장과 종사자,의료사회복지사,법원
0,2013,중앙,0,0,0,0,0,0,0,0,0,0,0,1,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0
1,2013,서울,87,17,27,0,21,0,1,1,1,0,9,215,0,0,NaN,0,15,4,1,12,2,0,1,20,5,7,26,184,4,42,217,103,5,198,15,1,0,NaN,63
2,2013,부산,54,2,10,0,9,0,0,0,1,2,22,50,0,0,NaN,0,2,0,1,7,2,0,0,2,2,5,4,88,4,12,48,16,0,60,8,2,0,NaN,14
3,2013,대구,39,6,29,0,5,5,0,0,0,3,4,12,0,0,NaN,0,1,0,1,14,8,0,0,2,3,4,10,60,1,12,20,21,0,122,4,3,0,NaN,15
4,2013,인천,31,7,10,4,5,0,0,1,0,7,16,75,0,0,NaN,1,29,1,2,15,3,0,0,1,1,0,3,56,2,19,80,54,0,88,4,0,0,NaN,21

### 2018년도 지역별 신고유형

In [ ]:
#'2018년'도 '강원도'의 신고유형 
report_type.loc[(report_type["기간"]==2018) & (report_type["구분"]=="강원")     ]

In [ ]:
#'2018년'도 '경기도'의 신고유형 
report_type.loc[(report_type["기간"]==2018) & (report_type["구분"]=="경기")     ]

In [ ]:
#'2018년'도 '경상남도'의 신고유형 
report_type.loc[(report_type["기간"]==2018) & (report_type["구분"]=="경남")     ]

In [ ]:
#'2018년'도 '경상북도'의 신고유형 
report_type.loc[(report_type["기간"]==2018) & (report_type["구분"]=="경북")     ]

In [ ]:
#'2018년'도 '광주광역시'의 신고유형 
report_type.loc[(report_type["기간"]==2018) & (report_type["구분"]=="광주")     ]

In [ ]:
#'2018년'도 '대구광역시'의 신고유형 
report_type.loc[(report_type["기간"]==2018) & (report_type["구분"]=="대구")     ]

In [ ]:
#'2018년'도 '대전광역시'의 신고유형 
report_type.loc[(report_type["기간"]==2018) & (report_type["구분"]=="대전")     ]

In [ ]:
#'2018년'도 '부산광역시'의 신고유형 
report_type.loc[(report_type["기간"]==2018) & (report_type["구분"]=="부산")     ]

In [160]:
#'2018년'도 '서울특별시'의 신고유형 
report_type.loc[(report_type["기간"]==2018) & (report_type["구분"]=="서울")     ]

,기간,구분,교직원,의료인,아동복지시설종사자,장애인복지시설종사자,보육교직원,"유치원교직원,강사",학원강사,소방구급대원,성매매피해시설상담소종사자,한부모가족복지시설종사자,가족폭력상담소보호시설종사자,사회복지전담공무원,아이돌보미,취약계층아동통합서비스지원인력,아동보호전문기관상담원,가정위탁지원센터종사자,아동복지전담공무원,건강가정지원센터종사자,다문화가족지원센터종사자,사회복지시설종사자,성폭력피해자보호시설종사자,응급구조사,의료기사,"청소년시설,단체종사자","청소년보호센터,재활센터종사자",정신보건센터종사자,아동본인,부모,"형제,자매",친인척,"이웃,친구",경찰,종교인,사회복지관련종사자,낯선사람,익명,아동보호전문기관장과 종사자,의료사회복지사,법원
86,2018,서울,702,40,34,7,20,10,2,6,0,4,5,50,30,0,14.0,2,1,1,0,24,19,0,9,6,1,0,455,844,51,64,211,24,7,40,54,20,523,5.0,0

In [ ]:
#'2018년'도 '세종특별시'의 신고유형 
report_type.loc[(report_type["기간"]==2018) & (report_type["구분"]=="세종")     ]

In [ ]:
#'2018년'도 '울산광역시'의 신고유형 
report_type.loc[(report_type["기간"]==2018) & (report_type["구분"]=="울산")     ]

In [ ]:
#'2018년'도 '인천광역시'의 신고유형 
report_type.loc[(report_type["기간"]==2018) & (report_type["구분"]=="인천")     ]

In [ ]:
#'2018년'도 '전라남도'의 신고유형 
report_type.loc[(report_type["기간"]==2018) & (report_type["구분"]=="전남")     ]

In [ ]:
#'2018년'도 '전라북도'의 신고유형 
report_type.loc[(report_type["기간"]==2018) & (report_type["구분"]=="전북")     ]

In [ ]:
#'2018년'도 '제주특별자치도'의 신고유형 
report_type.loc[(report_type["기간"]==2018) & (report_type["구분"]=="제주")     ]

In [ ]:
#'2018년'도 '충청남도'의 신고유형 
report_type.loc[(report_type["기간"]==2018) & (report_type["구분"]=="충남")     ]

In [ ]:
#'2018년'도 '충청북도'의 신고유형 
report_type.loc[(report_type["기간"]==2018) & (report_type["구분"]=="충북")     ]

## 2018년도. 지역별 건수 비교

In [ ]:
# 2018년도 서울 
Seoul_2018= y2018.loc[]

case=  y2018.loc[      ( y2018["아동학대의심사례 응급아동학대의심사례"]    )   &     ( y2018["아동학대의심사례"] )           ]

df.loc[(df["시군구명"]=="강남구") & (df["상권업종대분류명"]=="음식"),
       "상권업종중분류명"].value_counts()

In [125]:
#2018년 '서울'
Seoul18= y2018.loc[y2018["구분"]=="서울"]
Seoul18

,기간,구분,아동학대의심사례 응급아동학대의심사례,아동학대의심사례,일반상담,동일신고,해외발생사례,교직원,의료인,아동복지시설종사자,장애인복지시설종사자,보육교직원,"유치원교직원,강사",학원강사,소방구급대원,성매매피해시설상담소종사자,한부모가족복지시설종사자,가족폭력상담소보호시설종사자,사회복지전담공무원,아이돌보미,취약계층아동통합서비스지원인력,아동보호전문기관상담원,가정위탁지원센터종사자,아동복지전담공무원,건강가정지원센터종사자,다문화가족지원센터종사자,사회복지시설종사자,성폭력피해자보호시설종사자,응급구조사,의료기사,"청소년시설,단체종사자","청소년보호센터,재활센터종사자",정신보건센터종사자,아동본인,부모,"형제,자매",친인척,"이웃,친구",경찰,종교인,사회복지관련종사자,낯선사람,익명,아동보호전문기관장과 종사자,의료사회복지사,법원
86,2018,서울,98,3285,237,43.0,0,702,40,34,7,20,10,2,6,0,4,5,50,30,0,14.0,2,1,1,0,24,19,0,9,6,1,0,455,844,51,64,211,24,7,40,54,20,523,5.0,0

In [137]:
#2018년 '서울'의 '신고건수'

#Seoul18.loc[:, ['','']]


data1=Seoul18.loc[:, ['아동학대의심사례 응급아동학대의심사례','아동학대의심사례']]
data1

    아동학대의심사례 응급아동학대의심사례  아동학대의심사례
86                   98      3285

In [141]:
data1.transpose()

                       86
아동학대의심사례 응급아동학대의심사례    98
아동학대의심사례             3285

In [122]:
# 2018년 아동학대의심사례
y2018["아동학대의심사례"]

85        0
86     3285
87     2178
88     1507
89     2088
90     1088
91     1086
92      848
93     8041
94     1392
95     1006
96     1766
97     1850
98     2025
99     2263
100    1239
101     589
102      94
Name: 아동학대의심사례, dtype: int64

In [110]:
#2018년도 서울
y2018.loc[y2018["구분"]=="서울"]

,기간,구분,아동학대의심사례 응급아동학대의심사례,아동학대의심사례,일반상담,동일신고,해외발생사례,교직원,의료인,아동복지시설종사자,장애인복지시설종사자,보육교직원,"유치원교직원,강사",학원강사,소방구급대원,성매매피해시설상담소종사자,한부모가족복지시설종사자,가족폭력상담소보호시설종사자,사회복지전담공무원,아이돌보미,취약계층아동통합서비스지원인력,아동보호전문기관상담원,가정위탁지원센터종사자,아동복지전담공무원,건강가정지원센터종사자,다문화가족지원센터종사자,사회복지시설종사자,성폭력피해자보호시설종사자,응급구조사,의료기사,"청소년시설,단체종사자","청소년보호센터,재활센터종사자",정신보건센터종사자,아동본인,부모,"형제,자매",친인척,"이웃,친구",경찰,종교인,사회복지관련종사자,낯선사람,익명,아동보호전문기관장과 종사자,의료사회복지사,법원
86,2018,서울,98,3285,237,43.0,0,702,40,34,7,20,10,2,6,0,4,5,50,30,0,14.0,2,1,1,0,24,19,0,9,6,1,0,455,844,51,64,211,24,7,40,54,20,523,5.0,0

In [ ]:
#행렬 전환  ==> 신고유형 max 찾기

In [ ]:
Seoul18["유형"]    #86을 '유형' 으로 이름바꿔 , 그리고 앞에'index' 추가

In [146]:
Seoul18.transpose()

                       86
기간                   2018
구분                     서울
아동학대의심사례 응급아동학대의심사례    98
아동학대의심사례             3285
일반상담                  237
동일신고                   43
해외발생사례                  0
교직원                   702
의료인                    40
아동복지시설종사자              34
장애인복지시설종사자              7
보육교직원                  20
유치원교직원,강사              10
학원강사                    2
소방구급대원                  6
성매매피해시설상담소종사자           0
한부모가족복지시설종사자            4
가족폭력상담소보호시설종사자          5
사회복지전담공무원              50
아이돌보미                  30
취약계층아동통합서비스지원인력         0
아동보호전문기관상담원            14
가정위탁지원센터종사자             2
아동복지전담공무원               1
건강가정지원센터종사자             1
다문화가족지원센터종사자            0
사회복지시설종사자              24
성폭력피해자보호시설종사자          19
응급구조사                   0
의료기사                    9
청소년시설,단체종사자             6
청소년보호센터,재활센터종사자         1
정신보건센터종사자               0
아동본인                  455
부모                    844
형제,자매                  51
친인척                    64
이웃,친구                 211
경찰                     24
종교인                     7
사회복지관련종사자              40
낯선사람                   54
익명                     20
아동보호전문기관장과 종사자        523
의료사회복지사                 5
법원                      0